// <auto-generated />
using System;
using MatchaLatte.Ordering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MatchaLatte.Ordering.Data.Migrations
{
    [DbContext(typeof(OrderingContext))]
    [Migration("20181205034322_AddGroup")]
    partial class AddGroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ordering")
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Groups.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("Remark")
                        .HasMaxLength(512);

                    b.Property<DateTime>("StartTime");

                    b.Property<Guid>("StoreId");

                    b.HasKey("GroupId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("ProductCategoryId");

                    b.Property<int>("Sequence");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Products.ProductItem", b =>
                {
                    b.Property<Guid>("ProductItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(32);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<Guid>("ProductId");

                    b.HasKey("ProductItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductItem");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Stores.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductCategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("Sequence");

                    b.Property<Guid>("StoreId");

                    b.HasKey("ProductCategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Stores.Store", b =>
                {
                    b.Property<Guid>("StoreId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Remark")
                        .HasMaxLength(512);

                    b.HasKey("StoreId");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Products.Product", b =>
                {
                    b.HasOne("MatchaLatte.Ordering.Domain.Stores.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Products.ProductItem", b =>
                {
                    b.HasOne("MatchaLatte.Ordering.Domain.Products.Product", "Product")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Stores.ProductCategory", b =>
                {
                    b.HasOne("MatchaLatte.Ordering.Domain.Stores.Store", "Store")
                        .WithMany("ProductCategories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Stores.Store", b =>
                {
                    b.OwnsOne("MatchaLatte.Ordering.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StoreId");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnName("City")
                                .HasMaxLength(32);

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnName("Country")
                                .HasMaxLength(32);

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnName("District")
                                .HasMaxLength(32);

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnName("PostalCode")
                                .HasMaxLength(8);

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnName("Street")
                                .HasMaxLength(128);

                            b1.HasKey("StoreId");

                            b1.ToTable("Store","Ordering");

                            b1.HasOne("MatchaLatte.Ordering.Domain.Stores.Store")
                                .WithOne("Address")
                                .HasForeignKey("MatchaLatte.Ordering.Domain.Address", "StoreId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("MatchaLatte.Ordering.Domain.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("StoreId");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnName("CountryCode")
                                .HasMaxLength(4);

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnName("PhoneNumber")
                                .HasMaxLength(32);

                            b1.Property<int>("PhoneType")
                                .HasColumnName("PhoneType");

                            b1.HasKey("StoreId");

                            b1.ToTable("Store","Ordering");

                            b1.HasOne("MatchaLatte.Ordering.Domain.Stores.Store")
                                .WithOne("Phone")
                                .HasForeignKey("MatchaLatte.Ordering.Domain.Phone", "StoreId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
