// <auto-generated />
using System;
using MatchaLatte.Ordering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MatchaLatte.Ordering.Data.Migrations
{
    [DbContext(typeof(OrderingContext))]
    [Migration("20190808080845_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ordering")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MatchaLatte.Common.Events.EventLog", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EventContent")
                        .IsRequired();

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("EventTypeNamespace")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("PublishCount");

                    b.Property<int>("PublishState");

                    b.HasKey("EventId");

                    b.ToTable("EventLog","Common");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Buyers.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Buyer");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<Guid>("BuyerId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("GroupId");

                    b.Property<int>("OrderStatus");

                    b.Property<DateTime?>("PaidOn");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GroupId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("OrderId");

                    b.Property<Guid>("ProductId");

                    b.Property<Guid>("ProductItemId");

                    b.Property<string>("ProductItemName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<decimal>("ProductItemPrice")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductItemId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Orders.OrderItemProductAccessory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("OrderItemId");

                    b.Property<Guid>("ProductAccessoryId");

                    b.Property<string>("ProductAccessoryName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<decimal>("ProductAccessoryPrice")
                        .HasColumnType("decimal(19, 4)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ProductAccessoryId");

                    b.ToTable("OrderItemProductAccessory");
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("MatchaLatte.Ordering.Domain.Orders.Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MatchaLatte.Ordering.Domain.Orders.OrderItemProductAccessory", b =>
                {
                    b.HasOne("MatchaLatte.Ordering.Domain.Orders.OrderItem")
                        .WithMany("OrderItemProductAccessories")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
