// <auto-generated />
using System;
using Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manager.Data.migrations.generic
{
    [DbContext(typeof(GenericContext))]
    [Migration("20180703033644_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Generic")
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Manager.Domain.Models.Generic.BusinessEntity", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("BusinessEntityId");

                    b.ToTable("BusinessEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BusinessEntity");
                });

            modelBuilder.Entity("Manager.Domain.Models.Generic.Person", b =>
                {
                    b.HasBaseType("Manager.Domain.Models.Generic.BusinessEntity");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("Gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.ToTable("Person");

                    b.HasDiscriminator().HasValue("Person");

                    b.HasData(
                        new { BusinessEntityId = 1, BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), FirstName = "管理員", Gender = 9, LastName = "超級" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
